---
name: feature-request
description: Suggest an idea for this project
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Describe the solution you'd like
        A clear and concise description of what you want to happen.
  - type: textarea
    id: solution-description
    attributes:
      label: Solution description
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Describe alternatives you've considered
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Additional context
        Add any other context or screenshots about the feature request here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
